config/routes.rb
Rails.application.routes.draw do
  resources :bugs do 
    resources :comments
  end
  resources :users
  get 'users/new'
  get 'bugs' => 'bug#index'
  get 'login' => 'users#login'
  get 'users' => 'users#index'
  get 'comments' => 'comments#index'
  get 'edit_comment' => 'comments#edit'
  
  get 'apropos' => 'bugtracker#apropos'

  root 'bugtracker#index'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
    has_many :comments
    validates :name, presence: true,
                length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bug
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:name, :effect)
    end
end

app/controllers/bugtracker_controller.rb
class BugtrackerController < ApplicationController
    def index
    end
    
    def apropos
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]

    def index
        @comments = Comment.all
    end
    
    def create
        @bug = Bug.find(params[:bug_id])
        @comment = @bug.comments.create(comment_params)
        redirect_to bugs_path(@bug)
    end
    
    def destroy
        @bug = Bug.find(params[:bug_id])
        @comment = @bug.comments.find(params[:id])
        @comment.destroy
        redirect_to bugs_path(@bug)
    end
    
    def delete
        @comment = Comment.find(params[:bug_id])
        @comment.destroy
        redirect_to comments_path
    end
    
    def edit
    end
    
    private
        # Use callbacks to share common setup or constraints between actions.
        def set_comment
          @comment = Comment.find(params[:id])
        end
    
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/bugtracker_helper.rb
module BugtrackerHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :effect %><br>
    <%= f.text_field :effect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bugs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Effect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.name %></td>
        <td><%= bug.effect %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @bug.name %></h1>

<p>
  <strong>Effect:</strong>
  <%= @bug.effect %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

<br/><br/>


<h2>Comments</h2>
<% @bug.comments.each do |comment| %>
  <p>
    <strong>Commenter : </strong>
    <%= comment.commenter %>
  </p>
  
  <p>
    <strong>Comment : </strong>
    <%= comment.body %>
  </p>
  
  <p>
    <button><%= link_to "Edit Comment", [comment.bug, comment],
    method: :edit %></button>
  </p>
  
  <p>
    <button><%= link_to "Destroy Comment", [comment.bug, comment],
    method: :delete,
    data: {confirm: "Are you sure?" } %></button>
  </p>
  
  <br/><br/>
<% end %>


<h2>Add a comment</h2>

<%= form_for([@bug, @bug.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %> <br/>
    <%= f.text_field :commenter %>
  </p>
  
  <p>
    <%= f.label :body %> <br/>
    <%= f.text_field :body %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/bugtracker/apropos.html.erb
<h1>À propos</h1>

app/views/bugtracker/index.html.erb
<h1>BugTracker</h1>

app/views/comments/index.html.erb
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bug</th>
      <th>Commenter</th>
      <th>Comment</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
          <% @bug = Bug.find(params[:id] = comment.bug) %>
        <td><%= @bug.name %></td>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><button><%= link_to 'Edit', edit_comment_path(comment) %></button></td>
        <td><button><%= link_to 'Destroy', comments_path, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <%= link_to "BACK TO INDEX", "https://rails-tutorial-paulgirardin.c9users.io/" %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "USERS", users_path %></li>
          <li><%= link_to "LOGIN", login_path %></li>
          <li><%= link_to "BUGS", bugs_path %></li>
          <li><%= link_to "À propos", apropos_path %></li>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bugtracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  
  <div class="container" style="margin-top:100px">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<form action="" method="get">
    Username : <input type="text" name="user" />
    Password : <input type="password" name="password" />
</form>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>